name: Telegram Notifications

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        run: |
          MESSAGE=$(printf "🚀 *Novo commit!*\n\n👤 *Autor:* %s\n📂 *Repo:* %s\n🌿 *Branch:* %s\n\n💬 *Mensagem:*\n\"%s\"\n\n🔗 [Ver commit](https://github.com/%s/commit/%s)" \
          "${{ github.actor }}" \
          "${{ github.repository }}" \
          "${GITHUB_REF#refs/heads/}" \
          "${{ github.event.head_commit.message }}" \
          "${{ github.repository }}" \
          "${{ github.sha }}")

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
